// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYdkz51JxK3KrZutEOD8Op4Pt5bWdmMSc',
    appId: '1:565372838119:web:258e388d5d2d2afdbdc242',
    messagingSenderId: '565372838119',
    projectId: 'nos-importas',
    authDomain: 'nos-importas.firebaseapp.com',
    storageBucket: 'nos-importas.appspot.com',
    measurementId: 'G-HEK3LVS7XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMxITadIwWQw6t1gSX7pndH1z-CAqxIs',
    appId: '1:565372838119:android:4150234c9b220a1fbdc242',
    messagingSenderId: '565372838119',
    projectId: 'nos-importas',
    storageBucket: 'nos-importas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDJNcU5xCecdxKOA__NBcmmdACcb5iRg',
    appId: '1:565372838119:ios:dbac4fe8e074343abdc242',
    messagingSenderId: '565372838119',
    projectId: 'nos-importas',
    storageBucket: 'nos-importas.appspot.com',
    iosClientId:
        '565372838119-plkgfsbimigame216db7vpd3uslvqh66.apps.googleusercontent.com',
    iosBundleId: 'com.example.nosimportas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDJNcU5xCecdxKOA__NBcmmdACcb5iRg',
    appId: '1:565372838119:ios:dbac4fe8e074343abdc242',
    messagingSenderId: '565372838119',
    projectId: 'nos-importas',
    storageBucket: 'nos-importas.appspot.com',
    iosClientId:
        '565372838119-plkgfsbimigame216db7vpd3uslvqh66.apps.googleusercontent.com',
    iosBundleId: 'com.example.nosimportas',
  );
}
